id: P202629CE
initial_creation_type: ocr
source_metadata:
  volumes:
    5c9fb7087f414a2d9a430d9b728bdbb7:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1734
      volume_number: 34
